### ISSUE TITLE
Week 2 Lab Assignments ready for grading

### ISSUE THREAD

**Issue by rherring2-matc** [madisoncollege-it-programs/python-scripting-rherring2-matc#1]
I want to say that the Git lab document is difficult to understand. It is very confusing and it gives very few screen shots for checks to see if the steps were completed correctly.  I have no Idea if my log files are correct because of this issue. In my experience these documents should be written for someone who has never done this action before, which I have never used github before.  This Lab could be revised to be more friendly to a person trying this for the first time. If you would like specific feedback just reach out to me. I had to do lots of googling to finish this.

**Comment by cethenmc** [comment]
Looks great!  Way to work through it after having difficulties with that POD in class.  Appreciate the feedback.  I plan to fix a lot of this up next summer when I get prep time.  ~Chris

**Comment by cethenmc** [comment]
Hi, Robert.  I just realized that you created one issue to include both assignments, so I reopened this Issue.  Assignment #1 received 100% of the points.  For week 2, assignment 2, I would like you to update your script so you can run it from the command line.

Your first line should always be the following for your scripts. In this way, if you are running from the command line it will know what interpreter to use. Will you please add this line to the top of your first-script.py code?

#!/usr/bin/env python3

Recall from the videos, you may also need to issue a chmod command to modify the rights to make it executable.

chmod u+x first-script.py

After this, you can execute from the command line.

./first-script.py

Please be so kind as to resubmit it, so...
    1. modify the file in NetLab with the added line at the top.
    2. update the file to be executable.
    3. add the file to staging (git add .)
    4. commit the file to your local repo. (git commit -m "changes requested to run from command line")
    5. push to the git hub repository (git push)
    6. reply to this same issue, saying you have completed these steps

Thanks.

~Chris

**Comment by rherring2-matc** [comment]
I have completed and uploaded the first-script.py with the changes

**Comment by cethenmc** [comment]
Hi, Robert.  This submission looks good.  Thanks!
