### ISSUE TITLE
Argparse Lab week 11 ready for grading

### ISSUE THREAD

**Issue by rherring2-matc** [madisoncollege-it-programs/python-scripting-rherring2-matc#14]

**Comment by cethenmc** [comment]
Okay, overall.  I don't think you tested the version you pushed to GitHub.  Lines 28 and 31 cause errors when you run it. I recorded a 7 out of 8 for now.  You can correct Lines 28 and 31 and also make the one argument required that is supposed to be.  Furthermore, defaults were not requested, but I am not taking points off for that.  If you decide to go in and clean these other things up, you can remove the unnecessary defaults (obviously, the boolean lines keep them).

Please let me know if you would like to just keep the 7 out of 8, or resubmit soon.

**Comment by cethenmc** [comment]
Thanks for letting me know before class yesterday that you plan to keep the 7 out of 8.  I am closing this ticket.
