### ISSUE TITLE
Week 5 File Data Interactions Lad Ready for Grading

### ISSUE THREAD

**Issue by rherring2-matc** [madisoncollege-it-programs/python-scripting-rherring2-matc#4]

**Comment by cethenmc** [comment]
Hi, Robert.  Fairly good attempt.  I will be recording a 5 out of 8 for now, but I would like you to resubmit for full credit.

In #1 and #2, you left out a print explaining what the length is counting for each.  Please relate that answer to the file.
In #3 you have some good answers, but the approach you took is not following the request to "save the full file contents one line at a time to a variable."

Please reach out if you have questions, or perhaps if you are at Thursday's lab we could cover it.

Thanks.

Chris

**Comment by rherring2-matc** [comment]
I must have missed that print on 1 and 2 that is not a problem to fix. I must have not understood the directions for 3. The lines in my code are being written one line at a time to a variable but it was not appending to complete an entire file it was overwriting the variable each time and summing each length. Are you telling me that you want the file to append to and put  the complete file in the variable and then do a length on it?

**Comment by cethenmc** [comment]
Yes, Robert.  That is the desire for number 3.  You save only a single line in your variable at a time, and the problem would like you to save the entire file contents.   You articulated that perfectly in your response.  I wish the assignment articulated it that well.  😊  It will next year.

Chris

[signature_146958654]
Chris Ethen| Information Technology Instructor
Madison College | 1701 Wright Street | Madison, WI  53704
P: 1.608.616.1099 | ***@***.******@***.***>

**Comment by cethenmc** [comment]
I really like the way you ended up doing this one.  Very cool!
