### ISSUE TITLE
Week 6 Boolean Lab Ready for Grading

### ISSUE THREAD

**Issue by rherring2-matc** [madisoncollege-it-programs/python-scripting-rherring2-matc#5]

**Comment by cethenmc** [comment]
Although # 1 and # 2 rendered the correct result for you, you did not follow what was requested.  I will record a 7.2 of 8 in the grade book for now.  If you would like to resubmit after correcting the first two, I will be happy to give full credit.  Please reply to this open ticket when you have modified, or if you plan to just keep the 7.2 (so I know either way).

**Comment by rherring2-matc** [comment]
I uploaded a revised boolean script with the first 2 line containing "and" instead of "=="

**Comment by cethenmc** [comment]
Perfect.  Thanks, Robert.  Switching to full credit in the grade book.
