### ISSUE TITLE
Week 7 Dictionaries Lab ready for grading

### ISSUE THREAD

**Issue by rherring2-matc** [madisoncollege-it-programs/python-scripting-rherring2-matc#7]

**Comment by cethenmc** [comment]
Nicely done, but you did miss one piece.  The intention of # 5 was to add two key:value pair to an existing (already established) dictionary.  Please remove them from step # 1 and put two lines in the script doing the addition of the two servers for full credit.  I will record a 7 of 8.  Please reply to this open Issue ticket with a note that you pushed the revised script or if you prefer keeping the 7.  Thanks. ~Chris

**Comment by rherring2-matc** [comment]
I uploaded updated Dictionaries script to add entries by python code not manual input
